# TO TRADE
SANDBOX = False
if SANDBOX :
    API_URL = 'https://api-public.sandbox.pro.coinbase.com'
elif not SANDBOX :
    API_URL = 'https://api.pro.coinbase.com'

CURRENCY_TO_BUY = 'LTC'
CURRENCY_TO_SELL = 'USD'
SPEND_PER_TRADE = 10.0

# SAVING THE DATA
ALL_CURRENCIES = ["BTC", "ETH", "ADA", "DOGE", "LINK", "DOT", "LTC"]
ALL_CURRENCIES.remove(CURRENCY_TO_BUY)
CURRENCY_PAIRS = [f'{CURRENCY_TO_BUY}-{CURRENCY_TO_SELL}', *[f'{CURRENCY}-{CURRENCY_TO_SELL}' for CURRENCY in ALL_CURRENCIES]]
GRANULARITY = 'hours'
GRANULARITY_IN_SECONDS = 3600 # minute = 60; hour = 3600
# POINTS_PER_DAY = 24 # 24 if minute
DAYS_BACK = 360
FOLDER_TO_SAVE = 'Data/Hourly_new'
